export const FETCH_NEWS_DATA_SUCCESS = 'FETCH_NEWS_DATA_SUCCESS';
export const FETCH_NEWS_DATA_FAILED = 'FETCH_NEWS_DATA_FAILED';
export const FETCH_NEWS_DATA_START = 'FETCH_NEWS_DATA_START';
export const UPDATE_SRCH_KEYWORD = 'UPDATE_SRCH_KEYWORD';
